'use client';

export const Features = () => {
  return (
    <section className="section" id="features">
      <div className="section-eyebrow">— CAPABILITIES</div>
      <h2 className="section-h2">Built for Real<br/>Threat Detection</h2>
      <p className="section-desc">Every component of SentinelAI is purpose-built for accurate, fast, explainable threat intelligence.</p>
      <div className="feat-grid">
        <div className="feat-card">
          <div className="feat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" strokeWidth="1.5"><path d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"/><polyline points="13 2 13 9 20 9"/></svg>
          </div>
          <div className="feat-title">Multi-Agent AI</div>
          <div className="feat-text">5 specialized agents each handle a distinct part of analysis — no single point of failure.</div>
        </div>
        <div className="feat-card">
          <div className="feat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" strokeWidth="1.5"><polyline points="22 12 18 12 15 21 9 3 6 12 2 12"/></svg>
          </div>
          <div className="feat-title">Real-Time Scoring</div>
          <div className="feat-text">Risk score computed live from domain signals, phishing patterns, and blacklist hits.</div>
        </div>
        <div className="feat-card">
          <div className="feat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" strokeWidth="1.5"><circle cx="12" cy="12" r="10"/><path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>
          </div>
          <div className="feat-title">Explainable Results</div>
          <div className="feat-text">Every threat flag is explained in plain language — not just a score, but the why behind it.</div>
        </div>
        <div className="feat-card">
          <div className="feat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" strokeWidth="1.5"><path d="M21 16V8a2 2 0 0 0-1-1.73l-7-4a2 2 0 0 0-2 0l-7 4A2 2 0 0 0 3 8v8a2 2 0 0 0 1 1.73l7 4a2 2 0 0 0 2 0l7-4A2 2 0 0 0 21 16z"/><polyline points="3.27 6.96 12 12.01 20.73 6.96"/><line x1="12" y1="22.08" x2="12" y2="12"/></svg>
          </div>
          <div className="feat-title">Deep Content Scan</div>
          <div className="feat-text">Real-time HTML/form analysis to detect credential harvesting and brand impersonation.</div>
        </div>
        <div className="feat-card">
          <div className="feat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" strokeWidth="1.5"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
          </div>
          <div className="feat-title">IP Reputation</div>
          <div className="feat-text">Live IP resolution and Geo-intelligence to identify server origins and VPN cloaking.</div>
        </div>
        <div className="feat-card">
          <div className="feat-icon">
            <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="var(--accent)" strokeWidth="1.5"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
          </div>
          <div className="feat-title">AI Briefing</div>
          <div className="feat-text">Concise, professional security briefs generated by local AI for every analyzed threat.</div>
        </div>
      </div>
    </section>
  );
};
